### ISSUE TITLE
bucket.counter() counterpart in Couchbase java SDK 3

### ISSUE THREAD

**Issue by AbhideepChakravarty** [couchbase/docs-sdk-java#195]
I don't find any example. And bucket.defaultCollection().increment() is giving syntax error because defaultCollection() returns Collection and not BinaryCollection. So how do we go about it?

**Comment by AbhideepChakravarty** [comment]
Solution is 👍 

bucket.defaultCollection().binary().increment().

Now sure why they made few things so complicated.

**Comment by RichardSmedley** [comment]
Yes, fixing with https://github.com/couchbase/docs-sdk-java/pull/196
.
For background on SDK 3.0 API changes, you might wish to take a look at some of the RFCs, should you have time:   https://github.com/couchbaselabs/sdk-rfcs

**Comment by daschl** [comment]
@AbhideepChakravarty the reason for splitting it into a `BinaryCollection` is that the Collection only has JSON operations and all ops that are not json related have been moved into its own sub-namespace to avoid confusion.

**Comment by AbhideepChakravarty** [comment]
@daschl Ok. Thank you for the details.
