### ISSUE TITLE
Java SDK 2.6 and 2.7 do not discuss compatibility with Couchbase 5.5.x or 6.0 Beta

### ISSUE THREAD

**Issue by s34gull** [couchbase/docs-sdk-java#4]
The current documentation does not indicate compatibility of Java SDK 2.6.x or 2.7.x with latest stable and beta releases of the server.

**Comment by RichardSmedley** [comment]
Thank you for pointing this out - although it was on this month's task list, I hadn't yet created a ticket to track it.
Ticket now created: https://issues.couchbase.com/browse/DOC-4238

**Comment by RichardSmedley** [comment]
Finished for Java:
https://docs.couchbase.com/java-sdk/2.7/compatibility-versions-features.html
