### ISSUE TITLE
Transactional subdocument operations mutateIn

### ISSUE THREAD

**Issue by cebrailinanc** [couchbase/docs-sdk-java#404]
Hi, 
i need to transactional mutateIn with multiple keys, 
I guess there's no solution. Could you help me?

**Comment by programmatix** [comment]
Hi - yes, sub-document operations (mutateIn and lookupIn) are not supported inside transactions at this time.  But (almost) everything you can do with sub-document operations, can be done with full-document documents (get-and-replace).
